### ISSUE TITLE
[Bug]: Issues when using with SDNext (From Dev team)

### ISSUE THREAD

**Issue by Aptronymist** [Bing-su/adetailer#466] opened 2024-01-08 18:07 UTC
### Describe the bug

This isn't necessarily a "bug" but it seemed the best option to pick.

[We at SDNext](https://github.com/vladmandic/automatic) have an issue with adetailer because it does not actually set its parameters as they are changed, it apparently does it when you click generate by intercepting the click on the generate button. We have expanded into having a whole new massive Control module/tab with a ton of the Controlnet-type options and we can't make adetailer use a different button so that it will function properly with that, which will be a big part of our UI going forward.

I'm hoping we can discuss that not being [hardcoded for text2img and img2img](https://github.com/Bing-su/adetailer/blob/92692191ab996db7c635ecd564573351899dfeac/scripts/!adetailer.py#L776C46-L776C46), or finding some way to make things work, as of course adetailer is incredibly popular and we would love to maintain compatibility with it for our users.

I'd love to get in contact with you if you're on discord to discuss this if you have the chance. Vlad is of course always happy to collaborate as usual.

Thank you for your wonderful extension, it's a treasure!

### Console logs, from start to end.

```Shell
none
```

**Comment by Bing-su** [comment] 2024-01-09 01:16
https://github.com/Bing-su/adetailer/commit/2bd4db94d5f36da78b71de0c1bfc7804d990adf2

Maybe reverting this commit will be enough?

**Comment by vladmandic** [comment] 2024-01-09 20:19
yes, reverting that commit solves it - can you do that?

there is an additional issue that initial values are not set until any value is changed. for example, just enabling adetailer is not sufficient since even if default model is printed in ui, its not applied to state until change event is triggered happens.

**Comment by Bing-su** [comment] 2024-01-18 23:03
> @Bing-su any updates on reverting that change?

v24.1.1, I added initial values and and as the value is changed, the states are reflected immediately.

**Comment by vladmandic** [comment] 2024-01-18 23:06
I'll test and update tomorrow - thanks!

**Comment by vladmandic** [comment] 2024-01-19 18:47
confirmed as resolved - thanks!
@Aptronymist since you've opened the issue, can you close it?

**Closed** 2024-01-19 20:47 UTC
Labels: bug
